name = "Melody"
uuid = "ae1d2869-362d-4c27-9d2a-c5a05fc58f5b"
authors = ["Ollecram-Friends"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
